---
title: R Survey Report
author: David Keyes
format: html
execute: 
  echo: false
  warning: false
  message: false
---



```{r}
library(tidyverse)
library(janitor)
library(scales)
```

```{r}
# Data from https://github.com/rstudio/r-community-survey

survey_data <-
  read_tsv("2020-combined-survey-final.tsv") |>
  clean_names()
```

```{r}
avg_r_enjoyment <-
  survey_data |>
  drop_na(qr_enjoyment) |>
  group_by(qcountry) |>
  summarize(
    avg_enjoyment = mean(qr_enjoyment),
    number_of_responses = n()
  ) |>
  filter(number_of_responses >= 50) |>
  arrange(desc(avg_enjoyment)) |>
  drop_na(qcountry) |>
  mutate(avg_enjoyment_formatted = number(avg_enjoyment, accuracy = 0.01))
```

# Introduction

This is a report on R enjoyment.

# Results

Here is a chart on average R enjoyment by country.

```{r}
ggplot(
  data = avg_r_enjoyment,
  mapping = aes(
    x = avg_enjoyment,
    y = qcountry,
    label = avg_enjoyment_formatted
  )
) +
  geom_col(fill = "#6cabdd") +
  geom_text(hjust = 1.2, color = "white") +
  theme_minimal() +
  labs(
    title = "Average Enjoyment of R on a 5-Point Scale Among Users\nAround the World",
    subtitle = "Only countries with 50 or more responses included",
    x = NULL,
    y = NULL
  )
```

# Conclusion

I hope you enjoyed my report.